[build]
    publish = "build/"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
  checkPaths = [
    '/index.html',
  ]

  # # optional config
  # ignoreDirectories = ['/admin']  # explicitly ignore these directories

  # resultMode = "warn" # is "error" by default
