name: Lighthouse

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master, testing ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Audit with Lighthouse
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build
      - name: Run Lighthouse against the static build dir
        uses: treosh/lighthouse-ci-action@v3
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: './lighthouserc.json'
