name: Lighthouse

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master, testing ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Audit with Lighthouse
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run build
      - run: lhci autorun --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
